### ISSUE TITLE
Unminified Version

### ISSUE THREAD

**Issue by bm2u** [kapetan/jquery-observe#6]
Hey, great work. An unminified version of your dist would be appreciated. Best regards, bm2u

**Comment by nicgutierrez** [comment]
Same here. Getting some errors and it's quite hard to debug and fix. Also, we can't contribute without the unminified version.

**Comment by dotnetchris** [comment]
While not perfect, here's a copy of the file unminified ala http://unminify.com/

https://gist.github.com/dotnetchris/9fb93f9105c9ec6638026d8f857211f8

**Comment by MiniDude22** [comment]
Though it is not intuitive index.js seems to be the un-minified version of it.

**Comment by kapetan** [comment]
Version 3.0.0 contains the unminified source
